site_name: Learning Indico
site_url: https://indico.docs.cern.ch
theme:
    name: material
    palette:
        # Palette toggle for light mode
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
use_directory_urls: true
repo_name: 'indico/indico-user-docs-cern'
repo_url: 'https://gitlab.cern.ch/indico/indico-user-docs-cern'
markdown_extensions:
    - admonition
extra_css:
    - stylesheets/extra.css
nav:
    - Introduction: index.md
    - Categories:
        - Introduction: categories/about.md
        - Creating a Category: categories/creating.md
        - Having an Overview: categories/overview.md
        - Managing a Category:
            - Introduction: categories/managing.md
            - Protection: categories/protection.md
            - Moderation: categories/moderation.md
            - Logging: categories/logging.md
    - Event Management:
        - Introduction to Events: events.md
        - Lectures:
            - Introduction: lectures/about.md
            - Creating a Lecture: lectures/creating.md
            - Adding Material to a Lecture: lectures/material.md
        - Meetings:
            - Introduction: meetings/about.md
            - Creating a Meeting: meetings/creating.md
            - Making a Timetable: meetings/timetable.md
            - Adding minutes to a Meeting: meetings/minutes.md
            - Adding material to a Meeting: meetings/material.md
        - Conferences:
            - Introduction: conferences/about.md
            - Defining the Programme: conferences/programme.md
            - Call for Abstracts: conferences/cfa.md
            - Submitting an Abstract: conferences/submitting.md
            - Reviewing Abstracts: conferences/reviewing.md
            - Configuring the Registration Process: conferences/registration_config.md
            - Registering at a Conference: conferences/registration.md
            - Customizing the Conference Menu: conferences/custom_menu.md
            - Customizing the Conference Page Layout: conferences/custom_layout.md
            - Editing: conferences/editing.md
            - Paper Peer Reviewing: conferences/peer_reviewing.md
    - Room Booking:
        - Introduction: room_booking/about.md
        - Accessing the Module: room_booking/accessing.md
        - Booking a Room: room_booking/booking.md
        - Searching and Booking: room_booking/search_and_book.md
        - Viewing your Bookings: room_booking/viewing_bookings.md
        - Blocking Rooms: room_booking/blocking.md
        - Summary of Feature Set: room_booking/features.md
        - Managing your Rooms: cern/gesloc.md
        - Glossary: room_booking/glossary.md
    - Event Surveys:
        - Introduction: surveys/about.md
        - Setting up a Survey: surveys/setup.md
        - Opening/Closing a Survey: surveys/opening.md
    - Other features:
        - Zoom Integration: plugins/zoom.md
        - Webcast/Recording Requests: cern/webcast_recording.md
        - Reminders: reminders.md
        - Importing into Calendaring tools: calendar_import.md
        - Using custom roles: custom_roles.md
        - Sharepoint: cern/sharepoint.md
        - Access to the CERN site: cern/cern_access.md
        - Videoconference Assistance: cern/vc_assistance.md
        - Room Assistance: cern/room_assistance.md
    - Plugins:
        - Zoom: plugins/zoom.md
    - FAQ: faq.md
