site_name: Learning Indico
theme: material
extra:
    palette:
        primary: blue
        accent: light blue
repo_name: 'indico/indico-user-docs'
repo_url: 'https://github.com/indico/indico-user-docs'
markdown_extensions:
    - admonition
extra_css:
    - stylesheets/extra.css
nav:
    - Introduction: index.md
    - Categories:
        - Introduction: categories/about.md
        - Creating a Category: categories/creating.md
        - Having an Overview: categories/overview.md
        - Managing a Category:
            - Introduction: categories/managing.md
            - Protection: categories/protection.md
            - Moderation: categories/moderation.md
            - Logging: categories/logging.md
    - Event Management:
        - Introduction to Events: events.md
        - Lectures:
            - Introduction: lectures/about.md
            - Creating a Lecture: lectures/creating.md
            - Adding Material to a Lecture: lectures/material.md
        - Meetings:
            - Introduction: meetings/about.md
            - Creating a Meeting: meetings/creating.md
            - Making a Timetable: meetings/timetable.md
            - Adding minutes to a Meeting: meetings/minutes.md
            - Adding material to a Meeting: meetings/material.md
        - Conferences:
            - Introduction: conferences/about.md
            - Defining the Programme: conferences/programme.md
            - Call for Abstracts: conferences/cfa.md
            - Submitting an Abstract: conferences/submitting.md
            - Reviewing Abstracts: conferences/reviewing.md
            - Configuring the Registration Process: conferences/registration_config.md
            - Registering at a Conference: conferences/registration.md
            - Customizing the Conference Menu: conferences/custom_menu.md
            - Customizing the Conference Page Layout: conferences/custom_layout.md
            - Editing: conferences/editing.md
            - Paper Peer Reviewing: conferences/peer_reviewing.md
            - Programme Codes: conferences/programme_codes.md
    - Room Booking:
        - Introduction: room_booking/about.md
        - Accessing the Module: room_booking/accessing.md
        - Booking a Room: room_booking/booking.md
        - Searching and Booking: room_booking/search_and_book.md
        - Viewing your Bookings: room_booking/viewing_bookings.md
        - Blocking Rooms: room_booking/blocking.md
        - Summary of Feature Set: room_booking/features.md
        - Glossary: room_booking/glossary.md
    - Event Surveys:
        - Introduction: surveys/about.md
        - Setting up a Survey: surveys/setup.md
        - Opening/Closing a Survey: surveys/opening.md
    - Other features:
        - Reminders: reminders.md
        - Importing into Calendaring tools: calendar_import.md
    - Plugins:
        - Zoom: plugins/zoom.md
    - FAQ: faq.md
